apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts
  namespace: argocd
spec:
  project: default
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source: 
    path: manifests/argo-rollouts/base
    repoURL: https://github.com/sick-clim/gitops-manifest
