apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts
  namespace: argocd
spec:
  project: default
  source: 
    path: gitops-manifest/manifests/argo-rollouts/base/
    repoURL: https://github.com/argoproj/argocd-example-apps.git
